[workspace]
members = ["adapters", "ports"]

[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
embassy-time = { workspace = true, features = ["generic-queue-8"] }
embedded-hal-mock = { workspace = true }
mockall = { workspace = true }
proptest = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true }