[package]
name = "bsp"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
defmt = ["embassy-stm32/defmt", "domain/defmt"]
log = ["embassy-stm32/log", "domain/log"]

[dependencies]
embassy-stm32 = { workspace = true }
domain = { workspace = true }
assign-resources = { workspace = true }
bbqueue = { workspace = true }
intrusive-collections = { workspace = true }
